import globals from "globals";

export default [
  {
    files: ["frontend/js/**/*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "script",
      globals: {
        ...globals.browser,
        // CDN libraries
        supabase: "readonly",
        lucide: "readonly",
        Chart: "readonly",
        mammoth: "readonly",
        pdfjsLib: "readonly",
        XLSX: "readonly",
        // IIFE globals (assigned on window by each module)
        supabaseClient: "writable",
        Router: "writable",
        Auth: "writable",
        App: "writable",
        DashboardPage: "writable",
        ProjetosPage: "writable",
        GestaoPage: "writable",
        SaldosPage: "writable",
        HoldersPage: "writable",
        FundingPage: "writable",
        MonitoramentoPage: "writable",
        PlanoTrabalhoPage: "writable",
        FechamentoPage: "writable",
        HubPage: "writable",
        AssistentePage: "writable",
        UsuariosPage: "writable",
        ImportQueue: "writable",
        Notifications: "writable",
        CrudPage: "writable",
        ChartBuilder: "writable",
        SimulationEngine: "writable",
        // pure-fns.js (window-bridged via <script type="module">)
        formatBRL: "readonly",
        formatDate: "readonly",
        toInputDate: "readonly",
        escapeAttr: "readonly",
        escapeAttrJs: "readonly",
        localISODate: "readonly",
        inferBalanceStatus: "readonly",
        generateMonthSeries: "readonly",
        calcProjectMonthly: "readonly",
        diffProjections: "readonly",
        parseBRL: "readonly",
        formatRendimento: "readonly",
        summarizeRendimento: "readonly",
        // parsers + components (window-bridged via <script type="module">)
        parseBalanceteText: "readonly",
        parsePtFromHtml: "readonly",
        PtFormatError: "readonly",
        detectPtModel: "readonly",
        parsePtFromPdfText: "readonly",
        mountPdfSplitView: "readonly",
        mountDocxSplitView: "readonly",
        parseBolsaSpreadsheet: "readonly",
        compareBolsaData: "readonly",
        // camada de IA (window-bridged via <script type="module">)
        CFTools: "readonly",
        CFAgent: "readonly",
        CFMarkdown: "readonly",
        // supabase-config.js utilities (attached to window)
        showToast: "readonly",
        createModal: "readonly",
        confirmAction: "readonly",
        handleSupabaseResponse: "readonly",
        exportToCSV: "readonly",
        rendimentoLegendaHTML: "readonly",
        detalheTecnico: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none" }],
      "no-redeclare": "off",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-duplicate-case": "error",
      "no-unreachable": "error",
      "no-constant-condition": "warn",
      "no-cond-assign": "error",
      "no-sparse-arrays": "warn",
      "no-template-curly-in-string": "warn",
      "no-async-promise-executor": "error",
      "no-unsafe-negation": "error",
      "no-useless-escape": "warn",
      eqeqeq: ["warn", "smart"],
      curly: ["warn", "multi-line"],
    },
  },
  {
    // Servidor MCP: pacote Node próprio, ES modules, top-level await. Nada a ver
    // com o frontend sem build — daí o bloco separado em vez de esticar o de cima.
    files: ["mcp/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: { ...globals.node },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none" }],
      "no-dupe-keys": "error",
      "no-unreachable": "error",
      "no-async-promise-executor": "error",
      eqeqeq: ["warn", "smart"],
    },
  },
  {
    files: [
      "frontend/js/pure-fns.js",
      "frontend/js/parsers/**/*.js",
      "frontend/js/components/**/*.js",
      "frontend/js/ai/**/*.js",
    ],
    languageOptions: {
      // 2022 pelo `catch {}` sem binding e pelo separador numérico (60_000),
      // ambos usados em js/ai/.
      ecmaVersion: 2022,
      sourceType: "module",
    },
  },
];
